version: '3.4'

networks:
    frontend:
    backend:

services:
    eventcatalog:
        build:
            context: .\EventCatalogAPI
            dockerfile: Dockerfile
        image: eventbrite/eventapi
        environment:
            DatabaseServer: mssqlserver
            DatabaseName: EventDB
            DatabaseUser: sa
            DatabaseUserPassword: EventApi(!)
            ExternalCatalogBaseUrl: http://localhost:5090
        ports:
            - "5090:80"
        container_name: eventapi
        networks:
            - backend
            - frontend
        depends_on:
            - mssqlserver

    cart:
        build:
            context: .\CartApi
            dockerfile: Dockerfile
        image: eventbrite/cartapi
        environment:
            IdentityUrl: http://10.0.0.94:5080
            ConnectionString: basket.data
        ports:
            - "5065:80"
        container_name: cartapi
        networks:
            - backend
            - frontend
        depends_on:
            - basket.data
            - tokenserver
            - rabbitmq

    order:
        build:
            context: .\OrderApi
            dockerfile: Dockerfile
        image: eventbrite/orderapi
        environment:
            IdentityUrl: http://10.0.0.94:5080
            SQLSERVER_HOST: eventdb
            SA_PASSWORD: EventApi(!)
            DATABASE: OrdersDb
        ports:
            - "5077:80"
        container_name: orderapi
        networks:
            - backend
            - frontend
        depends_on:
            - mssqlserver
            - tokenserver
            - rabbitmq

    tokenserver:
        build:
            context: .\TokenServiceApi
            dockerfile: Dockerfile
        image: eventbrite/tokenapi
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            MvcClient: http://localhost:5070
        ports:
            - "5080:80"
        container_name: tokenapi
        networks:
            - backend
            - frontend
        depends_on:
            - mssqlserver

    webmvc:
        build:
            context: .\WebMvc
            dockerfile: Dockerfile
        image: eventbrite/webmvc
        container_name: EventWebshop
        environment:
            EventCatalogUrl: http://eventcatalog
            IdentityUrl: http://10.0.0.94:5080
            CallBackUrl: http://localhost:5070
            StripePublicKey: pk_test_jZlpubvlPmcV6QJPReImelQy
            StripePrivateKey: sk_test_bSHT9qxwjpyCOP0qdAvHLfAA
            ASPNETCORE_ENVIRONMENT: Development
        ports:
            - "5070:80"
        networks:
            - frontend
        depends_on:
            - eventcatalog
            - tokenserver

    mssqlserver:
        image: "mcr.microsoft.com/mssql/server:2019-CTP3.1-ubuntu"
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: EventApi(!)
        container_name: eventdb
        ports:
            - "1443:1433"
        networks:
            - backend

    basket.data:
        image: redis
        ports:
            - "6378:6379"
        networks:
            - backend

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        hostname: myrabbitmq
        ports:
          - "15672:15672"
          - "5672:5672"
          - "5671:5671"
        volumes:
          - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
        networks:
          - backend 