using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EventCatalogAPI.Domains
{
    public class EventItems
    {
        public int EventId { get; set; } //EventId will be Autogenerated primary key
        public string EventName { get; set; }
        public string EventCategory { get; set; } //Music, Kids, Drama, Outdoor, Dance, Food, Wine, Seminars)
        public string EventDescription { get; set; }
        public string EventVenue { get; set; }
        public string  EventAddress { get; set; }
        public string EventCity { get; set; }
        public string EventState { get; set; }
        public int Eventzip { get; set; }
        public bool EventFavorite { get; set; } // EventFavorite will be set to False by default
        public int EventTicketsAvailable { get; set; } // Total tickets available will be set to 100 by default
        public DateTime EventStartDatetime { get; set; } // example 07/12/2019 10:00  
        public DateTime EventEndDateTime { get; set; } // example 07/12/2019 05:00 
        public string EventPictureUrl { get; set; } //picture for the Event to be created
        public string EventUrl { get; set; } // website of the hosting party


        //This is tied to  and EventCategory (like Catalog Type
        public int EventCategoryId { get; set; } //foregin key



        //this is tied to EventVenue
        public int EventVenueId { get; set; } //foreign key

    }
}
